Public Class FrmAccountJournalError
    Dim sQuery As String = "
SELECT m.`Type`,m.date,m.code,m.notes,m.contact_name,l.`NAME` AS `LOCATION_NAME` FROM account_journal AS a INNER JOIN 
(
SELECT * FROM (
SELECT '23' AS OBJECT_TYPE,I.`ID` ,'Invoice' AS `TYPE`, I.DATE, I.`LOCATION_ID`,I.`CUSTOMER_ID` AS CONTACT_ID,I.`CODE`,I.`NOTES`,c.NAME AS CONTACT_NAME  FROM INVOICE AS I INNER JOIN contact AS c  ON c.`ID` = i.`CUSTOMER_ID` UNION
SELECT '24' AS OBJECT_TYPE,II.`ID`,'Invoice' AS `TYPE`, I.DATE, I.`LOCATION_ID`,I.`CUSTOMER_ID` AS CONTACT_ID,I.`CODE`,I.`NOTES`,c.NAME AS CONTACT_NAME  FROM INVOICE AS I INNER JOIN INVOICE_ITEMS AS II ON ii.`INVOICE_ID` = i.`ID` INNER JOIN contact AS c  ON c.`ID` = i.`CUSTOMER_ID`
) AS MYINVOICE UNION
SELECT * FROM (
SELECT '12' AS OBJECT_TYPE,CM.`ID`,'Credit Memo' AS `TYPE`, CM.DATE, CM.`LOCATION_ID`,CM.`CUSTOMER_ID` AS CONTACT_ID,CM.`CODE`,CM.`NOTES`,c.NAME AS CONTACT_NAME  FROM CREDIT_MEMO AS CM INNER JOIN contact AS c  ON c.`ID` = CM.`CUSTOMER_ID` UNION 
SELECT '13' AS OBJECT_TYPE,CMI.`ID`,'Credit Memo' AS `TYPE`, CM.DATE, CM.`LOCATION_ID`,CM.`CUSTOMER_ID` AS CONTACT_ID,CM.`CODE`,CM.`NOTES`,c.NAME AS CONTACT_NAME  FROM CREDIT_MEMO AS CM INNER JOIN CREDIT_MEMO_ITEMS AS CMI ON CMI.CREDIT_MEMO_ID = CM.ID INNER JOIN contact AS c  ON c.`ID` = CM.`CUSTOMER_ID`
) AS MYCREDIT_MEMO UNION
SELECT * FROM (
SELECT '52' AS OBJECT_TYPE,SR.`ID`,'Sales Receipt' AS `TYPE`, SR.DATE, SR.`LOCATION_ID`,SR.`CUSTOMER_ID` AS CONTACT_ID,SR.`CODE`,SR.`NOTES`,c.NAME AS CONTACT_NAME  FROM SALES_RECEIPT AS SR INNER JOIN contact AS c  ON c.`ID` =SR.`CUSTOMER_ID`UNION
SELECT '53' AS OBJECT_TYPE,SRI.`ID`,'Sales Receipt' AS `TYPE`, SR.DATE, SR.`LOCATION_ID`,SR.`CUSTOMER_ID` AS CONTACT_ID,SR.`CODE`,SR.`NOTES`,c.NAME AS CONTACT_NAME  FROM SALES_RECEIPT AS SR INNER JOIN SALES_RECEIPT_ITEMS AS SRI ON SRI.SALES_RECEIPT_ID = SR.ID INNER JOIN contact AS c  ON c.`ID` = SR.`CUSTOMER_ID`
) AS MYSALES_RECEIPT UNION
SELECT * FROM (
SELECT '72' AS OBJECT_TYPE,TC.`ID`, 'Tax Credit' AS `TYPE`,TC.DATE, TC.`LOCATION_ID`,TC.`CUSTOMER_ID` AS CONTACT_ID,TC.`CODE`,TC.`NOTES`,c.NAME AS CONTACT_NAME  FROM TAX_CREDIT AS TC INNER JOIN contact AS c  ON c.`ID` = TC.`CUSTOMER_ID` UNION
SELECT '73' AS OBJECT_TYPE,TCI.`ID`,'Tax Credit' AS `TYPE`, TC.DATE, TC.`LOCATION_ID`,TC.`CUSTOMER_ID` AS CONTACT_ID,TC.`CODE`,TC.`NOTES`,c.NAME AS CONTACT_NAME  FROM TAX_CREDIT AS TC INNER JOIN TAX_CREDIT_INVOICES AS TCI ON TCI.TAX_CREDIT_ID = TC.ID INNER JOIN contact AS c  ON c.`ID` = TC.`CUSTOMER_ID`
) AS MYTAX_CREDIT UNION
SELECT * FROM (
SELECT '41' AS OBJECT_TYPE,PM.`ID`,'Payment Received' AS `TYPE`, PM.DATE, PM.`LOCATION_ID`,PM.`CUSTOMER_ID` AS CONTACT_ID,PM.`CODE`,PM.`NOTES`,c.NAME AS CONTACT_NAME  FROM PAYMENT AS PM INNER JOIN contact AS c  ON c.`ID` = PM.`CUSTOMER_ID` UNION
SELECT '42' AS OBJECT_TYPE,PMI.`ID`,'Payment Received' AS `TYPE`, PM.DATE, PM.`LOCATION_ID`,PM.`CUSTOMER_ID` AS CONTACT_ID,PM.`CODE`,PM.`NOTES`,c.NAME AS CONTACT_NAME  FROM PAYMENT AS PM INNER JOIN PAYMENT_INVOICES AS PMI ON PMI.PAYMENT_ID = PM.ID INNER JOIN contact AS c  ON c.`ID` = PM.`CUSTOMER_ID`
) AS MYPAYMENT UNION
SELECT * FROM (
SELECT '2' AS OBJECT_TYPE,B.`ID`,'Bill' AS `TYPE`, B.DATE, B.`LOCATION_ID`,B.`VENDOR_ID` AS CONTACT_ID,B.`CODE`,B.`NOTES`,c.NAME AS CONTACT_NAME  FROM BILL AS B INNER JOIN contact AS c  ON c.`ID` =B.`VENDOR_ID` UNION
SELECT '3'  AS OBJECT_TYPE,BI.`ID`,'Bill' AS `TYPE`, B.DATE, B.`LOCATION_ID`,B.`VENDOR_ID` AS CONTACT_ID,B.`CODE`,B.`NOTES`,c.NAME AS CONTACT_NAME  FROM BILL AS B INNER JOIN  BILL_ITEMS AS BI ON BI.BILL_ID = B.ID INNER JOIN contact AS c  ON c.`ID` = B.`VENDOR_ID` UNION
SELECT '78' AS OBJECT_TYPE,BI.`ID`,'Bill' AS `TYPE`, B.DATE, B.`LOCATION_ID`,B.`VENDOR_ID` AS CONTACT_ID,B.`CODE`,B.`NOTES`,c.NAME AS CONTACT_NAME  FROM BILL AS B INNER JOIN  BILL_EXPENSES AS BI ON BI.BILL_ID = B.ID INNER JOIN contact AS c  ON c.`ID` = B.`VENDOR_ID`
) AS MYBILL UNION
SELECT * FROM (
SELECT '59' AS OBJECT_TYPE,BC.`ID`,'Bill Credit' AS `TYPE`, BC.DATE, BC.`LOCATION_ID`,BC.`VENDOR_ID` AS CONTACT_ID,BC.`CODE`,BC.`NOTES`,c.NAME AS CONTACT_NAME  FROM BILL_CREDIT AS BC INNER JOIN contact AS c  ON c.`ID` = BC.`VENDOR_ID` UNION
SELECT '60' AS OBJECT_TYPE,BCI.`ID`,'Bill Credit' AS `TYPE`, BC.DATE, BC.`LOCATION_ID`,BC.`VENDOR_ID` AS CONTACT_ID,BC.`CODE`,BC.`NOTES`,c.NAME AS CONTACT_NAME  FROM BILL_CREDIT AS BC INNER JOIN BILL_CREDIT_ITEMS AS BCI ON BCI.BILL_CREDIT_ID = BC.ID INNER JOIN contact AS c  ON c.`ID` = BC.`VENDOR_ID`UNION
SELECT '80' AS OBJECT_TYPE,BCI.`ID`,'Bill Credit' AS `TYPE`, BC.DATE, BC.`LOCATION_ID`,BC.`VENDOR_ID` AS CONTACT_ID,BC.`CODE`,BC.`NOTES`,c.NAME AS CONTACT_NAME  FROM BILL_CREDIT AS BC INNER JOIN BILL_CREDIT_EXPENSES AS BCI ON BCI.BILL_CREDIT_ID = BC.ID INNER JOIN contact AS c  ON c.`ID` = BC.`VENDOR_ID`
) AS MYBILL_CREDIT UNION
SELECT * FROM (
SELECT '57' AS OBJECT_TYPE,BP.`ID`,'Bill Payment' AS `TYPE`, BP.DATE, BP.`LOCATION_ID`,BP.`PAY_TO_ID` AS CONTACT_ID,BP.`CODE`,BP.`NOTES`,c.NAME AS CONTACT_NAME  FROM `CHECK` AS BP INNER JOIN contact AS c  ON c.`ID` = BP.`PAY_TO_ID` WHERE BP.`TYPE` ='1'  UNION
SELECT '58' AS OBJECT_TYPE,BPI.`ID`,'Bill Payment' AS `TYPE`, BP.DATE, BP.`LOCATION_ID`,BP.`PAY_TO_ID` AS CONTACT_ID,BP.`CODE`,BP.`NOTES`,c.NAME AS CONTACT_NAME  FROM `CHECK` AS BP INNER JOIN check_bills AS BPI ON BPI.BILL_ID = BP.ID INNER JOIN contact AS c  ON c.`ID` = BP.`PAY_TO_ID` WHERE BP.`TYPE` = '1'
) AS MYBILL_PAYMENT  UNION
SELECT * FROM (
SELECT '70' AS OBJECT_TYPE,BA.`ID`,'Build Assembly' AS `TYPE`, BA.DATE, BA.`LOCATION_ID`,'' AS CONTACT_ID,BA.`CODE`,BA.`NOTES`,'' AS CONTACT_NAME  FROM BUILD_ASSEMBLY AS BA UNION
SELECT '71' AS OBJECT_TYPE,BAI.`ID`,'Build Assembly' AS `TYPE`, BA.DATE, BA.`LOCATION_ID`,'' AS CONTACT_ID,BA.`CODE`,BA.`NOTES`,'' AS CONTACT_NAME  FROM BUILD_ASSEMBLY AS BA INNER JOIN BUILD_ASSEMBLY_ITEMS AS BAI ON BAI.`BUILD_ASSEMBLY_ID` = BA.ID  
) AS MYBUILD_ASSEMBLY UNION
SELECT '84' AS OBJECT_TYPE,GJD.`ID`,'General Journal' AS `TYPE`, GJ.DATE, GJ.`LOCATION_ID`,'' AS CONTACT_ID,GJ.`CODE`,GJ.`NOTES`,'' AS CONTACT_NAME  FROM GENERAL_JOURNAL AS GJ INNER JOIN GENERAL_JOURNAL_DETAILS AS GJD ON GJD.GENERAL_JOURNAL_ID = GJ.ID UNION
SELECT * FROM (
SELECT '19' AS OBJECT_TYPE,IA.`ID`, 'Inventory Adjustment' AS `TYPE`,IA.DATE, IA.`LOCATION_ID`,'' AS CONTACT_ID,IA.`CODE`,IA.`NOTES`,'' AS CONTACT_NAME  FROM INVENTORY_ADJUSTMENT AS IA UNION
SELECT '20' AS OBJECT_TYPE,IAI.`ID`,'Inventory Adjustment' AS `TYPE`, IA.DATE, IA.`LOCATION_ID`,'' AS CONTACT_ID,IA.`CODE`,IA.`NOTES`,'' AS CONTACT_NAME  FROM INVENTORY_ADJUSTMENT AS IA INNER JOIN INVENTORY_ADJUSTMENT_ITEMS AS IAI ON IAI.INVENTORY_ADJUSTMENT_ID = IA.ID 
) AS MYINVENTORY_ADJUSTMENT UNION
SELECT * FROM (
SELECT '38' AS OBJECT_TYPE,ST.`ID`,'Stock Transfer' AS `TYPE`, ST.DATE, ST.`LOCATION_ID`,'' AS CONTACT_ID,ST.`CODE`,ST.`NOTES`,C.`NAME` AS CONTACT_NAME  FROM STOCK_TRANSFER AS ST LEFT OUTER JOIN contact AS c  ON c.`ID` = ST.`PREPARED_BY_ID` UNION
SELECT '39' AS OBJECT_TYPE,STI.`ID`,'Stock Transfer' AS `TYPE`, ST.DATE, ST.`LOCATION_ID`,'' AS CONTACT_ID,ST.`CODE`,ST.`NOTES`,C.`NAME` AS CONTACT_NAME  FROM STOCK_TRANSFER AS ST INNER JOIN STOCK_TRANSFER_ITEMS AS STI ON STI.STOCK_TRANSFER_ID = ST.ID LEFT OUTER JOIN contact AS c  ON c.`ID` = ST.`PREPARED_BY_ID`
) AS MYSTOCK_TRANFER UNION
SELECT * FROM (
SELECT '57' AS OBJECT_TYPE,WC.`ID`,'Write Check' AS `TYPE`, WC.DATE, WC.`LOCATION_ID`,WC.`PAY_TO_ID` AS CONTACT_ID,WC.`CODE`,WC.`NOTES`,c.NAME AS CONTACT_NAME  FROM `CHECK` AS WC INNER JOIN contact AS c  ON c.`ID` = WC.`PAY_TO_ID` WHERE WC.`TYPE` ='0' UNION 
SELECT '75' AS OBJECT_TYPE,CI.`ID`,'Write Check' AS `TYPE`, WC.DATE, WC.`LOCATION_ID`,WC.`PAY_TO_ID` AS CONTACT_ID,WC.`CODE`,WC.`NOTES`,c.NAME AS CONTACT_NAME  FROM `CHECK` AS WC INNER JOIN CHECK_ITEMS  AS CI ON CI.CHECK_ID = WC.ID INNER JOIN contact AS c  ON c.`ID` = WC.`PAY_TO_ID` WHERE WC.`TYPE` ='0' UNION 
SELECT '79' AS OBJECT_TYPE,CI.`ID`,'Write Check' AS `TYPE`, WC.DATE, WC.`LOCATION_ID`,WC.`PAY_TO_ID` AS CONTACT_ID,WC.`CODE`,WC.`NOTES`,c.NAME AS CONTACT_NAME  FROM `CHECK` AS WC INNER JOIN CHECK_EXPENSES  AS CI ON CI.CHECK_ID = WC.ID INNER JOIN contact AS c  ON c.`ID` = WC.`PAY_TO_ID` WHERE WC.`TYPE` ='0' 
) AS MYWRITE_CHECK UNION
SELECT * FROM (
SELECT '81' AS OBJECT_TYPE,D.`ID`,'Deposit' AS `TYPE`, D.DATE, D.`LOCATION_ID`,'' AS CONTACT_ID,D.`CODE`,D.`NOTES`,'' AS CONTACT_NAME  FROM DEPOSIT AS D UNION
SELECT '82' AS OBJECT_TYPE,DF.`ID`,'Deposit' AS `TYPE`, D.DATE, D.`LOCATION_ID`,'' AS CONTACT_ID,D.`CODE`,D.`NOTES`,c.`NAME` AS CONTACT_NAME  FROM DEPOSIT AS D INNER JOIN DEPOSIT_FUNDS AS DF ON DF.`DEPOSIT_ID` = D.ID INNER JOIN account AS C ON C.ID = D.`BANK_ACCOUNT_ID`
) AS MYDEPOSIT UNION
SELECT '93' AS OBJECT_TYPE,FTF.`ID`,'Fund Transfer' AS `TYPE`, FTF.DATE, FTF.FROM_LOCATION_ID AS `LOCATION_ID`,FTF.FROM_NAME_ID AS CONTACT_ID,FTF.`CODE`,FTF.`NOTES`,lx.NAME AS CONTACT_NAME  FROM FUND_TRANSFER AS FTF  INNER JOIN LOCATION AS lx ON lx.ID = FTF.FROM_NAME_ID

) AS M 
ON (m.OBJECT_TYPE = a.OBJECT_TYPE AND a.OBJECT_ID = m.ID AND a.`OBJECT_DATE` = m.DATE)
INNER JOIN location AS L ON l.`ID`=  a.`LOCATION_ID` INNER JOIN account AS acct ON acct.ID = a.`ACCOUNT_ID`

WHERE EXISTS 
  (SELECT 
    j.`ID`
  FROM
    account_journal AS j 
  WHERE j.JOURNAL_NO <> a.`JOURNAL_NO` 
    AND j.`OBJECT_TYPE` = a.`OBJECT_TYPE` 
    AND j.`OBJECT_ID` = a.`OBJECT_ID` 
    AND j.`ENTRY_TYPE` = a.`ENTRY_TYPE` 
    AND j.`OBJECT_DATE` = a.`OBJECT_DATE` 
    AND J.`ACCOUNT_ID` = a.`ACCOUNT_ID` 
    AND J.LOCATION_ID = a.`LOCATION_ID`)
GROUP BY m.`Type`,m.date,m.code,m.contact_id,a.location_id,m.notes,m.contact_name
"

    Private Sub BtnReferesh_Click(sender As Object, e As EventArgs) Handles btnReferesh.Click
        GS_LoadDataGridViewStandard(dgvCLASS, sQuery)
        lblTotal.Text = "Total Record " & dgvCLASS.Rows.Count
    End Sub

    Private Sub FmAccountJournalError_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        lblTotal.Text = "Total Record " & dgvCLASS.Rows.Count
    End Sub

    Private Sub DgvCLASS_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgvCLASS.CellContentClick

    End Sub

    Private Sub DgvCLASS_CellDoubleClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgvCLASS.CellDoubleClick
        Dim ref As String = dgvCLASS.Rows(e.RowIndex).Cells(2).Value
        FrmMainMenu.txtSearch.Text = ref
        FrmMainMenu.fQuickSearch()

    End Sub
End Class